name: semana10
description: "Proyecto Flutter inspirado en Disney+"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Imágenes locales
  assets:
    - assets/images/

  # 3 tipos de letra 
  fonts:
    - family: Disney
      fonts:
        - asset: assets/fonts/Walter.ttf
    - family: TitleFont
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: TextFont
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
